### ISSUE TITLE
Page per category/tag

### ISSUE THREAD

**Issue by jcuenod** [wowthemesnet/mediumish-theme-jekyll#128]
I have a lot of posts (more than I want to list on a single page). Would it be possible to generate a page for each category/tag?

**Comment by MihajloNesic** [comment]
Yes. It's not that hard to implement :)

This theme already has **jekyll-archive** which is great! There's support for categories. You can navigate to `/category/{category_name}` to view archive of posts with that category.

To implement the tags, inside `_config.yml` file, replace the jekyll-archive part with this

```yml
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: archive
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'
```
