### ISSUE TITLE
post URL format

### ISSUE THREAD

**Issue by giswqs** [wowthemesnet/mediumish-theme-jekyll#14]
The URL of each post contains the categories it belongs to, making it very long when a post is assigned to multiple categories, such as 

http://example.com/category1/category2/category3/YYYY/MM/DD/title-of-the-post.html

Is it possible to eliminate categories from the URL and change the date format to YYYY-MM-DD, such as

http://example.com/YYYY-MM-DD-title-of-the-post.html

Many thanks!

**Comment by achmiral** [comment]
Hi, 
You can change the post URL by adding the `permalink` attribute to the `_config.yml` as shown below

```yaml
# _config.yml
...
baseurl: /mediumish-theme-jekyll
google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
mailchimp-list: 'https://wowt'
permalink: /:year-:month-:day-:title
...
```
